/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import custompanel.ImagePanel;
import databases.DBConnection;
import java.sql.Connection;
import javax.swing.ImageIcon;

/**
 *
 * @author iyefreed
 */
public class AdminPanel extends ImagePanel {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        super(new ImageIcon("src\\assets\\images\\hris_background.png").getImage());
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        admReimbursePanel1 = new GUI.AdmReimbursePanel();
        admTimeOffPanel1 = new GUI.AdmTimeOffPanel();
        admPayrollPanel1 = new GUI.AdmPayrollPanel();
        admPegawaiPanel1 = new GUI.AdmPegawaiPanel();

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTabbedPane1.addTab("Pengajuan Reimburse", admReimbursePanel1);
        jTabbedPane1.addTab("Pengajuan Cuti", admTimeOffPanel1);
        jTabbedPane1.addTab("Payroll Pegawai", admPayrollPanel1);
        jTabbedPane1.addTab("Daftar Pegawai", admPegawaiPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.AdmPayrollPanel admPayrollPanel1;
    private GUI.AdmPegawaiPanel admPegawaiPanel1;
    private GUI.AdmReimbursePanel admReimbursePanel1;
    private GUI.AdmTimeOffPanel admTimeOffPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
