/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import databases.DBConnection;
import java.awt.event.ItemEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author iyefreed
 */
public class AdmPegawaiPanel extends javax.swing.JPanel {
    Connection conn = new DBConnection().connect();
    Map<String, Object> roleItems = new HashMap<>();
    Map<String, Object> deptItems = new HashMap<>();
    String regId;
    /**
     * Creates new form AdmPanel
     */
    public AdmPegawaiPanel() {
        initComponents();
        setMap();
        loadPegawai();
        
        comboLimit.addItemListener(((e) -> {
            if(e.getStateChange() == ItemEvent.SELECTED) {
                loadPegawai();
            }
        }));
    }
    
    private void loadPegawai() {
        System.out.println("Load Pegawai");
        Object[] tHead = {"No.", "NIP", "Nama", "Departemen", "Role"};
        DefaultTableModel tableModel = new DefaultTableModel(null, tHead);
        tablePegawai.setModel(tableModel);
        String query = "SELECT * FROM t_pegawai LIMIT ?";
//        
//        deptItems.forEach((t, u) -> {
//            System.out.println(t.toString());
//            System.out.println(u.toString());
//        });
        
        try {
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setInt(1, Integer.parseInt(comboLimit.getSelectedItem().toString()));
            ResultSet result = stmt.executeQuery();
            
            int i = 1;
            while(result.next()) {
//                System.out.println(deptItems.get(result.getString("dept_id")));
                String a = result.getString("nip");
                String b = result.getString("t_pegawai.nama");
                String deptId = result.getString("dept_id");
                String roleId = result.getString("role_id");
                String c = deptItems.get(deptId).toString();
                String d = roleItems.get(roleId).toString();
                
                Object[] data = {i, a, b, c, d};
                tableModel.addRow(data);
                i++;
            }
        } catch(SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void setMap() {
//        Map<Integer, Object> deptItem = new HashMap<>();
        System.out.println("Map Settled");
        deptItems.put("1", "Marketing");
        deptItems.put("2", "Sales");
        deptItems.put("3", "Operator");
        deptItems.put("5", "Accounting");
        deptItems.put("6", "Tax");
        deptItems.put("8", "Network");
        deptItems.put("9", "System");
        deptItems.put("10", "R&D");
//        Map<Integer, Object> roleItem = new HashMap<>();
        roleItems.put("1", "Administrator");
        roleItems.put("2", "Staff");
    }
    
    private Object[] getValueArray(Map<String, Object> map) {
        return map.values().toArray();
    }
    
    private String getKey(Map<String, Object> map, Object value) {
        return map.entrySet().stream().filter(entry -> value.equals(entry.getValue())).map(Map.Entry::getKey).findFirst().get();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboLimit = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePegawai = new javax.swing.JTable();
        buttonAdd = new javax.swing.JButton();
        buttonPrint = new javax.swing.JButton();

        comboLimit.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        comboLimit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "15", "20", "25" }));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel1.setText("Show");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setText("Entries");

        tablePegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePegawai);

        buttonAdd.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/baseline_add_black_18dp.png"))); // NOI18N
        buttonAdd.setText("Tambah Data");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonPrint.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        buttonPrint.setText("Print");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPrint)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAdd)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(buttonAdd)
                    .addComponent(buttonPrint))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
//        Object[] deptItem = {"Marketing", "Sales", "Operator", "Accounting", "Tax", "Network", "System", "R&D"};
//        Object[] roleItem = {"Administrator", "Staff"};
        
        JTextField fieldNIP = new JTextField();
        JTextField fieldUsername = new JTextField();
        JTextField fieldPassword = new JTextField();
        JTextField fieldNama = new JTextField();
        JComboBox comboDepartemen = new JComboBox(getValueArray(deptItems));
        JComboBox comRole = new JComboBox(getValueArray(roleItems));
        final JComponent[] inputs = {
            new JLabel("NIP"),
            fieldNIP,
            new JLabel("Username"),
            fieldUsername,
            new JLabel("Password"),
            fieldPassword,
            new JLabel("Nama"),
            fieldNama,
            new JLabel("Role"),
            comRole,
            new JLabel("Departemen"),
            comboDepartemen
        };
        
        comRole.addItemListener((e)-> {
           if(e.getStateChange() == ItemEvent.SELECTED)  {
               System.out.println(getKey(roleItems, e.getItem().toString()));
           }
        });
        
        comboDepartemen.addItemListener((e) -> {
            if(e.getStateChange() == ItemEvent.SELECTED)  {
               System.out.println(getKey(deptItems, e.getItem().toString()));
           }
        });
        
        int result = JOptionPane.showConfirmDialog(this, inputs, "Tambah Data Pegawai", JOptionPane.PLAIN_MESSAGE);
        
        if(result == JOptionPane.OK_OPTION) {
            String query = "INSERT INTO t_pegawai(username, password, role_id, dept_id, nip, nama, no_ktp, jen_kel, tempat_lahir, tanggal_lahir, agama, email, no_telp, alamat, gol_darah) VALUES (?, ?, ?, ?, ?, ?, '', '', '', NOW(), '', '', '', '', 'A')";
            
            try {
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setString(1, fieldUsername.getText());
                stmt.setString(2, fieldPassword.getText());
                stmt.setString(3, getKey(roleItems, comRole.getSelectedItem().toString()));
                stmt.setString(4, getKey(deptItems, comboDepartemen.getSelectedItem().toString()));
                stmt.setString(5, fieldNIP.getText());
                stmt.setString(6, fieldNama.getText());
                
                stmt.execute();
                
                JOptionPane.showMessageDialog(this, "Berhasil menambah data pegawai");
                loadPegawai();
                
            }catch(SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        try {
            String fileName = "src\\report\\report_gaji.jasper";
            
            File file = new File(fileName);
            JasperReport reportAbsen = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportAbsen, null, conn);
            JasperViewer.viewReport(jasperPrint);
            
        } catch(JRException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_buttonPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonPrint;
    private javax.swing.JComboBox<String> comboLimit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePegawai;
    // End of variables declaration//GEN-END:variables
}
