/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import databases.DBConnection;
import java.awt.event.ItemEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author iyefreed
 */
public class AdmPayrollPanel extends javax.swing.JPanel {
    Connection conn = new DBConnection().connect();
    Date date = new Date();

    /**
     * Creates new form AdmPayrollPanel
     */
    public AdmPayrollPanel() {
        initComponents();
        loadPayrollTable();
        
        comboBulan.setSelectedIndex(date.getMonth());
        
        comboBulan.addItemListener((ItemEvent e) -> {
            if(e.getStateChange() == ItemEvent.SELECTED) {
                loadPayrollTable();
            }
        });
    }
    
    private void loadPayrollTable() {
        Object[] tHead = {"No.", "Nama Pegawai", "Nominal", "Tanggal Terima"};
        DefaultTableModel tableModel = new DefaultTableModel(null, tHead);
        tablePayroll.setModel(tableModel);
        
        String query = "SELECT * FROM t_gaji JOIN t_pegawai WHERE t_gaji.pegawai_id=t_pegawai.id AND t_gaji.bulan=? AND YEAR(t_gaji.created_at)=?";
        
        try {
            DecimalFormat kurs = (DecimalFormat) DecimalFormat.getCurrencyInstance();
            DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
            formatRp.setCurrencySymbol("Rp. ");
            formatRp.setMonetaryDecimalSeparator(',');
            formatRp.setGroupingSeparator('.');
            kurs.setDecimalFormatSymbols(formatRp);
            
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, comboBulan.getSelectedItem().toString());
            stmt.setString(2, comboTahun.getSelectedItem().toString());
            
            ResultSet result = stmt.executeQuery();
            
            int i = 1;
            while(result.next()) {
                String a = result.getString("nama") ;
                String b = kurs.format(Double.parseDouble(result.getString("nominal")));
                String c = result.getString("created_at");
                
                Object[] data = {i, a, b, c};
                tableModel.addRow(data);
                i++;
            }
        } catch(SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBulan = new javax.swing.JComboBox<>();
        comboTahun = new javax.swing.JComboBox<>();
        buttonPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePayroll = new javax.swing.JTable();

        comboBulan.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        comboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        comboTahun.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        comboTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018" }));

        buttonPrint.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        buttonPrint.setText("Print");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });

        tablePayroll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePayroll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comboTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPrint)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPrint))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        try {
            String fileName = "src\\report\\report_gaji.jasper";
            
            File file = new File(fileName);
            JasperReport reportAbsen = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportAbsen, null, conn);
            JasperViewer.viewReport(jasperPrint);
            
        } catch(JRException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_buttonPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPrint;
    private javax.swing.JComboBox<String> comboBulan;
    private javax.swing.JComboBox<String> comboTahun;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePayroll;
    // End of variables declaration//GEN-END:variables
}
