/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import custompanel.ImagePanel;
import java.sql.PreparedStatement;
import java.sql.Connection;
import databases.DBConnection;
import java.awt.event.ItemEvent;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author iyefreed
 */
public class AdmTimeOffPanel extends ImagePanel {
    Connection conn = new DBConnection().connect();
    Object[] tHead = {"No.", "Tanggal Mulai", "Tanggal Akhir", "Pengganti", "Keperluan", "Status"};
    DefaultTableModel tableModel = new DefaultTableModel(null, tHead);
    String status;
    /**
     * Creates new form AdmTimeOffPanel
     */
    public AdmTimeOffPanel() {
        super(new ImageIcon("src\\assets\\images\\hris_background.png").getImage());
        initComponents();
        status = comboStatus.getSelectedItem().toString();
        initTable(status);
        
        comboStatus.addItemListener((e) -> {
            if(e.getStateChange() == ItemEvent.SELECTED) {
                status = e.getItem().toString();
                initTable(status);
            }
        });
    }
    
     private void initTable(String status) {
        admReimburseTable.setModel(tableModel);
        
        String query = "SELECT * FROM t_cuti WHERE status=?";
        if(status.equals("SEMUA")) query = "SELECT * FROM t_cuti";
        
        try {
            PreparedStatement stmt = conn.prepareStatement(query);
            if(!status.equals("SEMUA")) stmt.setString(1, status);
            ResultSet result = stmt.executeQuery();
            int i = 1;
            while(result.next()) {
                String b = result.getString("tanggal_mulai");
                String c = result.getString("tanggal_akhir");
                String d = result.getString("pengganti_nama");
                String e = result.getString("keterangan");
                String f = result.getString("status");
                
                Object[] data = {i, b, c, d, e, f};
                
                tableModel.addRow(data);
                i++;
            }
        } catch(SQLException e) {
            System.err.println(e.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        admReimburseTable = new javax.swing.JTable();
        buttonAcc = new javax.swing.JButton();
        Tolak = new javax.swing.JButton();
        comboStatus = new javax.swing.JComboBox<>();
        buttonPrint = new javax.swing.JButton();

        admReimburseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Tanggal Mulai", "Tanggal Akhir", "Pengganti", "Keperluan", "Status"
            }
        ));
        admReimburseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admReimburseTableMouseClicked(evt);
            }
        });
        admReimburseTable.getColumnModel().getColumn(0).setPreferredWidth(1);
        jScrollPane1.setViewportView(admReimburseTable);
        if (admReimburseTable.getColumnModel().getColumnCount() > 0) {
            admReimburseTable.getColumnModel().getColumn(0).setMaxWidth(10);
        }

        buttonAcc.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        buttonAcc.setText("Setujui");
        buttonAcc.setEnabled(false);
        buttonAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccActionPerformed(evt);
            }
        });

        Tolak.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        Tolak.setText("Tolak");
        Tolak.setEnabled(false);
        Tolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TolakActionPerformed(evt);
            }
        });

        comboStatus.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMUA", "MENUNGGU", "SETUJU", "BATAL" }));

        buttonPrint.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        buttonPrint.setText("Print");
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPrint))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAcc)
                        .addGap(18, 18, 18)
                        .addComponent(Tolak)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPrint))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tolak)
                    .addComponent(buttonAcc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void admReimburseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admReimburseTableMouseClicked
        buttonAcc.setEnabled(true);
        Tolak.setEnabled(true);
    }//GEN-LAST:event_admReimburseTableMouseClicked

    private void buttonAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccActionPerformed
        String query = "UPDATE t_cuti SET status='SETUJU' WHERE id=?";

        try {
            int row = admReimburseTable.getSelectedRow();
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, tableModel.getValueAt(row, 0).toString());

            stmt.execute();
            JOptionPane.showMessageDialog(this, "Pengajuan Disetujui");
            initTable(status);
        } catch(SQLException e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_buttonAccActionPerformed

    private void TolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TolakActionPerformed
        String query = "UPDATE t_cuti SET status='BATAL' WHERE id=?";

        try {
            int row = admReimburseTable.getSelectedRow();
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, tableModel.getValueAt(row, 0).toString());

            stmt.execute();
            JOptionPane.showMessageDialog(this, "Pengajuan Ditolak");
            initTable(status);
        } catch(SQLException e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_TolakActionPerformed

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
                                      
        try {
            String fileName = "src\\report\\report_cuti.jasper";
            
            File file = new File(fileName);
            JasperReport reportAbsen = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportAbsen, null, conn);
            JasperViewer.viewReport(jasperPrint);
            
        } catch(JRException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_buttonPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tolak;
    private javax.swing.JTable admReimburseTable;
    private javax.swing.JButton buttonAcc;
    private javax.swing.JButton buttonPrint;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
