/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import custompanel.ImagePanel;
import databases.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.YearMonth;
import java.util.Date;
import javax.swing.ImageIcon;
import utils.UserSession;

/**
 *
 * @author iyefreed
 */
public class DashboardPanel extends ImagePanel {
    Connection conn = new DBConnection().connect();
    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        super(new ImageIcon("src\\assets\\images\\hris_background.png").getImage());
        initComponents();
        loadData();
        loadPanel();
    }
    
    private void loadPanel() {
        String query1 = "SELECT MONTHNAME(tanggal_lahir) AS bulan FROM t_pegawai WHERE MONTHNAME(tanggal_lahir)=MONTHNAME(NOW())";
        
        try {
            PreparedStatement stmt = conn.prepareStatement(query1);
            
            ResultSet result = stmt.executeQuery();
            
            int i = 0;
            while(result.next()) {
                i++;
                jLabel9.setText(Integer.toString(i));
            }
        } catch(SQLException e) {
            e.printStackTrace();
        }
        
        String query2 = "SELECT * FROM t_pegawai JOIN t_absen WHERE t_pegawai.id=t_absen.pegawai_id AND t_pegawai.id=? AND MONTHNAME(t_absen.tanggal)=MONTHNAME(NOW())";
        
        try {
            PreparedStatement stmt = conn.prepareStatement(query2);
            stmt.setString(1, UserSession.getId());
            stmt.executeQuery();
            ResultSet result = stmt.executeQuery();
            
            int i = 0;
            while(result.next()) {
                i++;
            }
            
            Date date = new Date();
            YearMonth yearMonth = YearMonth.of(date.getYear(), date.getMonth()+1);
            int daysInMonth = yearMonth.lengthOfMonth();
            
            double attendancePercentage = (double) i / daysInMonth * 100;
            System.out.println(i + " / " + daysInMonth + " * " + 1);
            System.out.println("Hasil Persentase : " + attendancePercentage);
            
            jLabel13.setText(Double.toString(attendancePercentage) + " %");
            
        } catch(SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void loadData() {
        
        String query = "SELECT * FROM t_pegawai JOIN t_departemen WHERE t_pegawai.dept_id=t_departemen.id AND t_pegawai.id=?";
        
        try {
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, UserSession.getId());
            ResultSet result = stmt.executeQuery();
            
            while(result.next()) {
                dashboardNama.setText(result.getString("nama"));
                dashboardEmail.setText(result.getString("email"));
                dashboardNotelp.setText(result.getString("no_telp"));
                dashboardUnit.setText(result.getString("t_departemen.nama"));
            }
            
        } catch(SQLException e) {
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dashboardNama = new javax.swing.JLabel();
        dashboardEmail = new javax.swing.JLabel();
        dashboardUnit = new javax.swing.JLabel();
        dashboardNotelp = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jPanel4.setBackground(new java.awt.Color(0, 255, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("0%");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 110, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel14.setText("Tingkat Kehadiran");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jPanel1.add(jPanel4);

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html>Karyawan yang berulang tahun bulan ini</html>");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("2");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 80, 300, -1));

        jPanel1.add(jPanel3);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 640, 170));

        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon("src\\assets\\images\\user.png"));
        jLabel6.setMaximumSize(new java.awt.Dimension(34, 50));
        jLabel6.setMinimumSize(new java.awt.Dimension(34, 50));
        jLabel6.setPreferredSize(new java.awt.Dimension(34, 50));
        jPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 150, 140));

        dashboardNama.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        dashboardNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardNama.setText("Muhammad Quraisy");
        dashboardNama.setMaximumSize(new java.awt.Dimension(500, 500));
        dashboardNama.setPreferredSize(new java.awt.Dimension(34, 200));
        jPanel11.add(dashboardNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 280, 30));

        dashboardEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        dashboardEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardEmail.setText("iye.fredickson@gmail.com");
        jPanel11.add(dashboardEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 280, -1));

        dashboardUnit.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        dashboardUnit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardUnit.setText("Backend Developer");
        jPanel11.add(dashboardUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 210, 280, -1));

        dashboardNotelp.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        dashboardNotelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardNotelp.setText("087880688799");
        jPanel11.add(dashboardNotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 280, -1));

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 320, 310));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardEmail;
    private javax.swing.JLabel dashboardNama;
    private javax.swing.JLabel dashboardNotelp;
    private javax.swing.JLabel dashboardUnit;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
