/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.github.lgooddatepicker.components.DatePickerSettings;
import custompanel.ImagePanel;
import databases.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utils.UserSession;

/**
 *
 * @author iyefreed
 */
public class InfoPegawaiPanel extends ImagePanel {
    Connection conn = new DBConnection().connect();
    /**
     * Creates new form InfoPegawaiPanel
     */
    public InfoPegawaiPanel() {
        super(new ImageIcon("src\\assets\\images\\hris_background.png").getImage());
        initComponents();
        loadData();
    }
    
    private void loadData() {
        
        String query = "SELECT * FROM t_pegawai WHERE t_pegawai.id=?";
        
        try {
            
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, UserSession.getId());
            ResultSet result = stmt.executeQuery();
            
            if(result.next()) {
                fieldNama.setText(result.getString("nama"));
                fieldEmail.setText(result.getString("email"));
                fieldNotelp.setText(result.getString("no_telp"));
                fieldTempatlahir.setText(result.getString("tempat_lahir"));
                fieldTanggallahir.setText(result.getString("tanggal_lahir"));
                fieldKTP.setText(result.getString("no_ktp"));
                fieldNIP.setText(result.getString("nip"));
                areaAlamat.setText(result.getString("alamat"));
                comboAgama.setSelectedItem(result.getString("agama"));
                comboGoldarah.setSelectedItem(result.getString("gol_darah"));

                if(result.getString("jen_kel").equals("Laki-Laki")) {
                    radioLaki.setSelected(true);
                } else {
                    radioPer.setSelected(true);
                }
            }
            
        } catch(SQLException e) {
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        buttonSaveProfile = new javax.swing.JButton();
        fieldNIP = new javax.swing.JTextField();
        fieldNama = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        fieldNotelp = new javax.swing.JTextField();
        fieldTempatlahir = new javax.swing.JTextField();
        comboGoldarah = new javax.swing.JComboBox<>();
        radioLaki = new javax.swing.JRadioButton();
        radioPer = new javax.swing.JRadioButton();
        comboAgama = new javax.swing.JComboBox<>();
        fieldKTP = new javax.swing.JTextField();
        buttonClearProfile = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaAlamat = new javax.swing.JTextArea();
        DatePickerSettings dateSettings = new DatePickerSettings();
        dateSettings.setFormatForDatesCommonEra("yyyy-MM-dd");
        fieldTanggallahir = new com.github.lgooddatepicker.components.DatePicker(dateSettings);

        jLabel6.setText("jLabel6");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel1.setText("Email");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel2.setText("Alamat");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel3.setText("Nama");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel4.setText("Nomor Induk Pegawai");
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 160, 20));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel5.setText("Nomor HP");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel20.setText("Nomor KTP");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, 20));

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel21.setText("Tempat & Tgl. Lahir");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel22.setText("Golongan Darah");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel23.setText("Jenis Kelamin");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel24.setText("Agama");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        buttonSaveProfile.setIcon(new javax.swing.ImageIcon("C:\\Users\\Muhammad Quraisy\\Downloads\\1x\\baseline_done_black_18dp.png")); // NOI18N
        buttonSaveProfile.setText("Simpan");
        buttonSaveProfile.setBackground(new java.awt.Color(0, 153, 255));
        buttonSaveProfile.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        buttonSaveProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveProfileActionPerformed(evt);
            }
        });
        add(buttonSaveProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, -1));

        fieldNIP.setEditable(false);
        fieldNIP.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        fieldNIP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));
        add(fieldNIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 310, -1));

        fieldNama.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        fieldNama.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.lightGray));
        add(fieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 310, -1));

        fieldEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        fieldEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 310, -1));

        fieldNotelp.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        fieldNotelp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        add(fieldNotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 310, -1));

        fieldTempatlahir.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        fieldTempatlahir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.gray));
        add(fieldTempatlahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 140, -1));

        comboGoldarah.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        comboGoldarah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        add(comboGoldarah, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        radioLaki.setText("Laki-Laki");
        radioLaki.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        add(radioLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        radioPer.setText("Perempuan");
        radioPer.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        add(radioPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        comboAgama.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        comboAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Katolik", "Protestan", "Hindu", "Buddha" }));
        add(comboAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        fieldKTP.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        fieldKTP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.lightGray));
        fieldKTP.setEnabled(false);
        add(fieldKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 310, -1));

        buttonClearProfile.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        buttonClearProfile.setText("Clear");
        add(buttonClearProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        areaAlamat.setColumns(20);
        areaAlamat.setRows(5);
        jScrollPane4.setViewportView(areaAlamat);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 320, 60));
        add(fieldTanggallahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaveProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveProfileActionPerformed
        String query = "UPDATE t_pegawai SET nama=?, email=?, no_telp=?, tempat_lahir=?, tanggal_lahir=?, gol_darah=?, jen_kel=?, agama=?, alamat=? WHERE id=?";
        
        try {
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, fieldNama.getText());
            stmt.setString(2, fieldEmail.getText());
            stmt.setString(3, fieldNotelp.getText());
            stmt.setString(4, fieldTempatlahir.getText());
            stmt.setString(5, fieldTanggallahir.getText());
            stmt.setString(6, comboGoldarah.getSelectedItem().toString());
            stmt.setString(7, radioLaki.isSelected() ? radioLaki.getText() : radioPer.getText());
            stmt.setString(8, comboAgama.getSelectedItem().toString());;
            stmt.setString(9, areaAlamat.getText());
            stmt.setString(10, UserSession.getId());
            
            stmt.execute();
            
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui");
        } catch(SQLException e) {
            System.err.println(e.toString());
        }
        
    }//GEN-LAST:event_buttonSaveProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaAlamat;
    private javax.swing.JButton buttonClearProfile;
    private javax.swing.JButton buttonSaveProfile;
    private javax.swing.JComboBox<String> comboAgama;
    private javax.swing.JComboBox<String> comboGoldarah;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldKTP;
    private javax.swing.JTextField fieldNIP;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldNotelp;
    private com.github.lgooddatepicker.components.DatePicker fieldTanggallahir;
    private javax.swing.JTextField fieldTempatlahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton radioLaki;
    private javax.swing.JRadioButton radioPer;
    // End of variables declaration//GEN-END:variables
}
