/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import utils.UserSession;

/**
 *
 * @author iyefreed
 */
public class MainFrame extends javax.swing.JFrame {
    

    /**
     * Creates new form MainForm
     */
    public MainFrame() {
        initComponents();
        setTitle("Menu HRIS - Andalas Media Informatika");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width / 2 - getSize().width / 2, dim.height / 2 - getSize().height / 2);
        System.out.println(UserSession.getId());
        System.out.println(UserSession.getDeptId());
        System.out.println(UserSession.getRoleId());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payrollPanel1 = new GUI.PayrollPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        dashboardPanel1 = new GUI.DashboardPanel();
        attendancePanel1 = new GUI.AttendancePanel();
        payrollPanel2 = new GUI.PayrollPanel();
        reimbursePanel2 = new GUI.ReimbursePanel();
        timeOffPanel1 = new GUI.TimeOffPanel();
        infoPegawaiPanel1 = new GUI.InfoPegawaiPanel();
        adminPanel1 = new GUI.AdminPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTabbedPane1.addTab("Dashboard", dashboardPanel1);
        jTabbedPane1.addTab("Attendance", attendancePanel1);
        jTabbedPane1.addTab("Payroll", payrollPanel2);
        jTabbedPane1.addTab("Reimburse", reimbursePanel2);
        jTabbedPane1.addTab("Time Off / Cuti", timeOffPanel1);
        jTabbedPane1.addTab("Profil", infoPegawaiPanel1);
        jTabbedPane1.addTab("Administrator", adminPanel1);

        if(!UserSession.getRoleId().equals("1")) {
            jTabbedPane1.remove(adminPanel1);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.AdminPanel adminPanel1;
    private GUI.AttendancePanel attendancePanel1;
    private GUI.DashboardPanel dashboardPanel1;
    private GUI.InfoPegawaiPanel infoPegawaiPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private GUI.PayrollPanel payrollPanel1;
    private GUI.PayrollPanel payrollPanel2;
    private GUI.ReimbursePanel reimbursePanel2;
    private GUI.TimeOffPanel timeOffPanel1;
    // End of variables declaration//GEN-END:variables
}
