/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import custompanel.ImagePanel;
import databases.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import utils.UserSession;

/**
 *
 * @author iyefreed
 */
public class ReimbursePanel extends ImagePanel {
    Connection conn = new DBConnection().connect();
    /**
     * Creates new form ReimbursePanel
     */
    public ReimbursePanel() {
        super(new ImageIcon("src\\assets\\images\\hris_background.png").getImage());
        initComponents();
        initData();
    }
    
    private void initData() {
        Object[] tHead = {"No.", "Nominal", "Keterangan", "Tanggal", "Status"};
        DefaultTableModel tableModel = new DefaultTableModel(null, tHead);
        tableReimburse.setModel(tableModel);
        
        try {
            DecimalFormat kurs = (DecimalFormat) DecimalFormat.getCurrencyInstance();
            DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
            formatRp.setCurrencySymbol("Rp. ");
            formatRp.setMonetaryDecimalSeparator(',');
            formatRp.setGroupingSeparator('.');
            kurs.setDecimalFormatSymbols(formatRp);
            
            String query = "SELECT * FROM t_reimburse WHERE pegawai_id=?";
            
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, UserSession.getId());
            
            ResultSet result = stmt.executeQuery();
            
            int i = 1;
            while(result.next()) {
                String a = kurs.format(Double.parseDouble(result.getString("nominal")));
                String b = result.getString("keterangan");
                String c = result.getString("created_at");
                String d = result.getString("status");
                
                Object[] data = {i, a, b, c, d};
                
                tableModel.addRow(data);
                i++;
            }
        } catch(SQLException e) {
            System.err.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableReimburse = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jComboBox2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "15", "20", "25" }));

        tableReimburse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableReimburse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor Peminjaman", "Tanggal Pengajuan Peminjaman", "Status", "Aksi"
            }
        ));
        tableReimburse.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableReimburse.setEnabled(false);
        jScrollPane2.setViewportView(tableReimburse);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel1.setText("Show");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setText("Entries");

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/baseline_add_black_18dp.png"))); // NOI18N
        jButton1.setText("Ajukan Peminjaman");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTextField fieldNominal = new JTextField();
        JTextArea fieldKeterangan = new JTextArea(5, 10);
        
        final JComponent[] inputs = new JComponent[] {
            new JLabel("Nominal"),
            fieldNominal,
            new JLabel("Keterangan"),
            fieldKeterangan
        };
        
        int result = JOptionPane.showConfirmDialog(this, inputs, "Form Pengajuan Reimburse", JOptionPane.PLAIN_MESSAGE);
        
        if(result == JOptionPane.OK_OPTION) {
            String query = "INSERT INTO t_reimburse (nominal, keterangan, pegawai_id) VALUES (?, ?, ?)";
        
            try {
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setString(1, fieldNominal.getText());
                stmt.setString(2, fieldKeterangan.getText());
                stmt.setString(3, UserSession.getId());

                stmt.execute();

                JOptionPane.showMessageDialog(this, "Reimburse berhasil diajukan");
                initData();
            } catch (SQLException e) {
                System.err.println(e.toString());
                JOptionPane.showMessageDialog(this, "Gagal Mengajukan" + e.toString());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableReimburse;
    // End of variables declaration//GEN-END:variables
}
