/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.github.lgooddatepicker.components.DatePicker;
import custompanel.ImagePanel;
import databases.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import utils.UserSession;

/**
 *
 * @author iyefreed
 */
public class TimeOffPanel extends ImagePanel {
    Connection conn = new DBConnection().connect();
    Map<String, String> penggantiId = new HashMap<>();
    /**
     * Creates new form TimeOffPanel
     */
    public TimeOffPanel() {
        super(new ImageIcon("src\\assets\\images\\hris_background.png").getImage());
        initComponents();
        initData();
    }
    
    private Object[] getPengganti() {
        
        try {
            String query = "SELECT t_pegawai.nama, t_pegawai.id FROM t_pegawai WHERE t_pegawai.dept_id=? AND t_pegawai.id <> ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, UserSession.getDeptId());
            stmt.setString(2, UserSession.getId());
            
            ResultSet result = stmt.executeQuery();
            System.out.println(result.getRow());
            while(result.next()) {
                penggantiId.put(result.getString("nama"), result.getString("id"));
            }
            
            Object[] items = penggantiId.keySet().toArray();
            
            return items;
        } catch(SQLException e) {
            return null;
        }
    }
    
    private void initData() {
        Object[] tHead = {"No.", "Tanggal Mulai", "Tanggal Akhir", "Keperluan", "Pegawai Pengganti", "Status"};
        DefaultTableModel tableModel = new DefaultTableModel(null, tHead);
        tableTimeOFf.setModel(tableModel);
        
        String query = "SELECT * FROM t_cuti WHERE pegawai_id=?";
        
        try {
            
            PreparedStatement stmt = conn.prepareStatement(query);
            
            stmt.setString(1, UserSession.getId());
            
            ResultSet result = stmt.executeQuery();
            
            int i = 1;
            while(result.next()) {
                String index = Integer.toString(i);
                String a = result.getString("tanggal_mulai");
                String b = result.getString("tanggal_akhir");
                String c = result.getString("keterangan");
                String d = result.getString("pengganti_nama");
                String e = result.getString("status");
                
                String[] data = {index, a, b, c, d, e};
                tableModel.addRow(data);
                i++;
            }
        } catch(SQLException e) {
            System.err.println(e.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tableTimeOFf = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        tableTimeOFf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nomor Cuti", "Tanggal Mulai Cuti", "Tanggal Akhir Cuti", "Pegawai Pengganti", "Status", "Aksi"
            }
        ));
        jScrollPane3.setViewportView(tableTimeOFf);

        jComboBox2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "15", "20", "25" }));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel1.setText("Show");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setText("Entries");

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/baseline_add_black_18dp.png"))); // NOI18N
        jButton1.setText("Ajukan Cuti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DatePicker fieldMulai = new DatePicker();
        DatePicker fieldAkhir = new DatePicker();
        JTextArea textKeperluan = new JTextArea(5, 10);
        JComboBox comboPengganti = new JComboBox(getPengganti());
        
        final JComponent[] inputs = new JComponent[] {
            new JLabel("Tanggal Mulai"),
            fieldMulai,
            new JLabel("Tanggal Akhir"),
            fieldAkhir,
            new JLabel("Keperluan"),
            textKeperluan,
            new JLabel("Pegawai Pengganti"),
            comboPengganti
        };
        
        int result = JOptionPane.showConfirmDialog(this, inputs, "Form Pengajuan Cuti", JOptionPane.PLAIN_MESSAGE);
        
        if(result == JOptionPane.OK_OPTION) {
            String query = "INSERT INTO t_cuti (pegawai_id, tanggal_mulai, tanggal_akhir, pengganti_id, pengganti_nama, keterangan) VALUES (?, ?, ?, ?, ?, ?)";
        
            try {
                // Memformat tanggal
                SimpleDateFormat sdf = new SimpleDateFormat("MMMM d, yyyy");
                java.util.Date dateMulai = sdf.parse(fieldMulai.getText());
                java.util.Date dateAkhir = sdf.parse(fieldAkhir.getText());
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                String sMulai = format.format(dateMulai);
                String sAkhir = format.format(dateAkhir);

                // Proses Query
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setString(1, UserSession.getId());
                stmt.setString(2, sMulai);
                stmt.setString(3, sAkhir);
                stmt.setString(4, penggantiId.get(comboPengganti.getSelectedItem().toString()));
                stmt.setString(5, comboPengganti.getSelectedItem().toString());
                stmt.setString(6, textKeperluan.getText());

                stmt.execute();
                initData();
                JOptionPane.showMessageDialog(this, "Cuti berhasil diajukan");
            } catch (SQLException | ParseException e) {
                System.err.println(e.toString());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableTimeOFf;
    // End of variables declaration//GEN-END:variables
}
